### ISSUE TITLE
Batch process fails

### ISSUE THREAD

**Issue by crouti** [njean42/kumiko#3]
Hello,
I am trying the batch process now, and it raises an error:

```
 /home/maxunger/ComicToVideo/kumiko/kumiko -i /var/www/ilurn.com/wp-content/uploads/comics_adventures/lesecretdelalicorne/ > ./lesecretdelalicorne.json
Traceback (most recent call last):
  File "/home/maxunger/ComicToVideo/kumiko/kumiko", line 27, in <module>
    info = k.parse_dir(file_or_folder)
  File "/home/maxunger/ComicToVideo/kumiko/kumikolib.py", line 39, in parse_dir
    return self.parse_images(filenames)
  File "/home/maxunger/ComicToVideo/kumiko/kumikolib.py", line 45, in parse_images
    infos.append(self.parse_image(filename))
  File "/home/maxunger/ComicToVideo/kumiko/kumikolib.py", line 53, in parse_image
    size = list(img.shape[:2])
AttributeError: 'NoneType' object has no attribute 'shape'
```

Can you please help ?

**Comment by crouti** [comment]
Solved, it was du to presence of folders inside source folder, maybe skip them by default ?
Cheers

**Comment by njean42** [comment]
Yes, I've had this problem too, when non-images files are present in the folder.
I've tried to know whether `cv.imread(filename)` succeeds or fails, with no luck so far...
